### ISSUE TITLE
Failed to initialise

### ISSUE THREAD

**Issue by mxmeinhold** [OpenTTD/steam-social#5]
Is there any way I can get further log output?

Trying to get this running on linux (Arch) with openttd 14.1, but seeing

```
[2024-12-15 04:26:15] dbg: [misc:1] [Social Integration: steam/libsteam-social.so] Loading ...
[S_API] SteamAPI_Init(): Loaded '/home/bionicpi/.local/share/Steam/linux64/steamclient.so' OK.
[2024-12-15 04:26:15] dbg: [misc:0] [Social Integration: steam/libsteam-social.so] Failed to initialize
```

Not sure where I might find more for debugging

**Comment by PeterN** [comment]
Are you launching OpenTTD from within Steam, or externally? The Steam API won't work for externally launched software.

**Comment by mxmeinhold** [comment]
that would make sense. I was trying to manage it with my standard package manager, and add it to Steam, because that is how I encountered it first, and had been hoping to continue using that, but there's no barrier to me installing via steam, so I'm just going to use Steam directly

thanks!
